import axios from 'axios';

const API_BASE = 'http://localhost:8000/api';

export const solveTask = async (task, language = 'python') => {
  try {
    const response = await axios.post(`${API_BASE}/solve`, {
      task,
      language,
      context: 'Generated by React Frontend'
    });
    return response.data;
  } catch (error) {
    throw error.response?.data || error.message;
  }
};

export const getTaskStatus = async (taskId) => {
  try {
    const response = await axios.get(`${API_BASE}/status/${taskId}`);
    return response.data;
  } catch (error) {
    throw error.response?.data || error.message;
  }
};